global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'pushart'
    static_configs:
      - targets: 
          - 'auth-service:8081'
          - 'account-service:8082'
          - 'author-service:8083'
          - 'content-service:8084'
          - 'custom-subscribe-service:8085'
          - 'csat-service:8086'

  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
rule_files:
  - 'alerts.yml'

