name: Docker CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "load" ]
env:
  IMAGE_REGISTRY: "ghcr.io"
jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint go
        run: go vet ./...
  tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: go.sum
    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose
    - name: Docker up for tests
      run: |
        cd ./cmd/microservices
        docker-compose up -d --build postgres
        docker-compose up -d --build migrate-service
        docker-compose up -d --build filling-service

    - name: Install dependencies
      run: go mod tidy
    - name: Tests
      run: go test ./...

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: whoami
