name: Docker-compose CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "load" ]

jobs:

  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint go
        run: go vet ./...

  tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: go.sum
    - name: Docker up for tests
      run: |
        cd ./cmd/microservices
        docker-compose up -d --build postgres
        docker-compose up -d --build migrate-service
        docker-compose up -d --build filling-service

    - name: Install dependencies
      run: go mod tidy
    - name: Tests
      run: go test ./...


#  deploy:
#    needs: tests
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Run command on remote server
#        uses: D3rHase/ssh-command-action@v0.2.2
#        with:
#          host: ${{secrets.SSH_HOST}}
#          user: ${{secrets.SSH_USER}}
#          private_key: ${{secrets.SSH_PRIVATE_KEY}}
#          command: |
#            cd ${{ secrets.PROJECT_FOLDER }};
#            git checkout load;
#            git pull;
#            docker-compose --file docker-compose.prod.yml down;
#            docker-compose --file docker-compose.prod.yml up -d;
#            docker system prune --all --force;
